
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace URUNTAKIPMVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Birim
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Birim()
    {

        this.Kullanicis = new HashSet<Kullanici>();

    }


    public int ID { get; set; }

    public string BirimAdı { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Kullanici> Kullanicis { get; set; }

}

}
