

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace URUNTAKIPMVC.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class MVCURUNYONETIMEntities : DbContext
{
    public MVCURUNYONETIMEntities()
        : base("name=MVCURUNYONETIMEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Birim> Birims { get; set; }

    public virtual DbSet<Dosyalar> Dosyalars { get; set; }

    public virtual DbSet<Durum> Durums { get; set; }

    public virtual DbSet<Kategori> Kategoris { get; set; }

    public virtual DbSet<Kullanici> Kullanicis { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<UrunGecmisi> UrunGecmisis { get; set; }

    public virtual DbSet<Urunler> Urunlers { get; set; }

}

}

