
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace URUNTAKIPMVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Urunler
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Urunler()
    {

        this.Dosyalars = new HashSet<Dosyalar>();

        this.UrunGecmisis = new HashSet<UrunGecmisi>();

    }


    public int ID { get; set; }

    public int KullaniciID { get; set; }

    public string Marka { get; set; }

    public string Model { get; set; }

    public string SeriNo { get; set; }

    public int DurumID { get; set; }

    public int KategoriID { get; set; }

    public int Fiyat { get; set; }

    public System.DateTime VerilenTarih { get; set; }

    public System.DateTime AlinanTarih { get; set; }

    public string notlar { get; set; }

    public bool atandiMi { get; set; }

    public int Adet { get; set; }

    public Nullable<bool> PDF { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Dosyalar> Dosyalars { get; set; }

    public virtual Durum Durum { get; set; }

    public virtual Kategori Kategori { get; set; }

    public virtual Kullanici Kullanici { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UrunGecmisi> UrunGecmisis { get; set; }

}

}
